Add commit format GitHub action
hms-networks/sc-java-maven-starter-project pull request #2
Opened 2021-08-02 18:24 UTC by alexjhawk

This new GitHub action will check to ensure that all commits in a pull request follow the required format, and if not, will fail to indicate to the user what the issue is.

2021-08-02 19:25 UTC, TomKimsey requested changes
You will probably want to comment the regexs used.

2021-08-02 19:25 UTC, TomKimsey commented on .github/workflows/commit-format-check.yml
> +          error: 'The title does not begin with a capitalized first character (or number).'
```suggestion
          error: 'The title must begin with a capitalized first character (or number).'
```

2021-08-02 19:25 UTC, TomKimsey commented on .github/workflows/commit-format-check.yml
> +          pattern: '^(.{0,72}(\r|\n|\r\n))*.{0,72}?$'
Why is the title being checked for length (72) here? its already been checked to be less than or equal to 50.

2021-08-02 19:25 UTC, TomKimsey commented on .github/workflows/commit-format-check.yml
> +          flags: 'gy'
What do these flags mean?

2021-08-02 20:46 UTC, alexjhawk commented on .github/workflows/commit-format-check.yml
> +          pattern: '^(.{0,72}(\r|\n|\r\n))*.{0,72}?$'
The title is not explicitly checked. This is blanket checking that no lines are > 72.

2021-08-02 20:46 UTC, alexjhawk commented on .github/workflows/commit-format-check.yml
> +          flags: 'gy'
added comment to clarify (and removed the g because I now learn that is redundant/unnecessary)

2021-08-02 20:46 UTC, alexjhawk commented on .github/workflows/commit-format-check.yml
> +          error: 'The title does not begin with a capitalized first character (or number).'
changed

2021-08-02 20:50 UTC, oliver-walker-hms approved these changes

2021-08-03 13:36 UTC, TomKimsey reviewed
I dont think my overall review comment got addressed or responded to, also looks like another commit got added that does not fall in the scope of the PR title.

2021-08-03 13:51 UTC, alexjhawk commented
> I dont think my overall review comment got addressed or responded to, also looks like another commit got added that does not fall in the scope of the PR title.

PR title changed. Regex now includes a comment

2021-08-03 13:51 UTC, TomKimsey approved these changes

2021-08-03 14:04 UTC, oliver-walker-hms approved these changes

2021-08-03 14:05 UTC, merged