v0.0.7 - Workflow Updates, Issue Templates, and Older Queued Up Changes
hms-networks/sc-java-maven-starter-project pull request #62
Opened 2024-02-08 16:13 UTC by alexjhawk

2024-02-08 16:21 UTC, alexjhawk commented
While this is not an exact rendering of the issue templates in this PR, an example of what they look like for reference is:

![image](https://github.com/hms-networks/sc-java-maven-starter-project/assets/51409174/f1f50a8f-4aae-42b1-bf2d-b33ae702b152)

Additionally, I've had the 'latest version display' component for Docusaurus coded and ready for quite a while, but I did not implement it anywhere in the live documentation. An preview of it in action is: 
![image](https://github.com/hms-networks/sc-java-maven-starter-project/assets/51409174/794cb862-76f3-4536-85eb-e5936351f719)

2024-02-08 18:57 UTC, TomKimsey commented on .github/workflows/release-push-maven-repo.yml
> +# HMS Networks Application Engineering
Is this the branding we want to go with vs "HMS Networks Inc" or "HMS Networks; Americas"

Adding this comment outside of review, im out of office tomorrow so i just want to get the discussion going on this.

2024-02-08 19:14 UTC, TomKimsey requested changes

2024-02-08 19:14 UTC, TomKimsey commented on .github/ISSUE_TEMPLATE/01-app-bug-report.yml
> +      description: 'A clear and concise description of what is currently happening. Please include any error messages or logs.'
We need to be careful about what information we solicit here, many of these repos are public and users may think they are submitting a confidential form.

2024-02-08 19:15 UTC, alexjhawk commented on .github/workflows/release-push-maven-repo.yml
> +# HMS Networks Application Engineering
I don't really have a preference and am open to changing it.

2024-02-08 19:30 UTC, alexjhawk commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +import React from "react";
Neither. I created this as a new component a while back in November 2023.

2024-02-08 19:52 UTC, alexjhawk commented on .github/workflows/release-push-maven-repo.yml
> +# HMS Networks Application Engineering
Changed to `HMS Networks; Americas` after discussion with @it-hms.

2024-02-08 19:52 UTC, TomKimsey commented on .github/workflows/release-push-maven-repo.yml
> +# HMS Networks Application Engineering
I dont think HMS Networks Application Engineering has any meaning. If it at least points to HMS Networks Inc. its clear its the Americas based entity. Other HMS entities have application and field application engineers.

2024-02-08 19:53 UTC, alexjhawk commented on .github/ISSUE_TEMPLATE/05-security-report.yml
> +name: Security Report
Guidance was added to the referenced comment here. There was already a notice about not publicly disclosing vulnerabilities in the below markdown portion, but I also expanded that.

2024-02-08 19:54 UTC, alexjhawk commented on .github/ISSUE_TEMPLATE/06-other-report.yml
> +    id: application-version
Added similar checkbox to bug report

2024-02-08 19:55 UTC, alexjhawk commented on .github/ISSUE_TEMPLATE/01-app-bug-report.yml
> +        If this issue is not easily reproducible, please take a backup of your Ewon including support files.
I added some language here that describes when best to take a backup.

2024-02-08 19:56 UTC, alexjhawk commented on .github/ISSUE_TEMPLATE/01-app-bug-report.yml
> +      description: 'A clear and concise description of what is currently happening. Please include any error messages or logs.'
Each of the templates now contains a `Privacy notice` section at the bottom which highlights the public nature of the corresponding GitHub issue created

2024-02-08 20:28 UTC, it-hms requested changes

2024-02-08 20:28 UTC, it-hms commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +      <div
style is applied to the containing div

2024-02-08 20:28 UTC, it-hms commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +  const versionText = latestVersionData.isLoading ? (
variable name is misleading. Version component?

2024-02-08 20:28 UTC, it-hms commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +      style={styles.version(
style is applied to p tag, but same styling to containing div.

2024-02-08 20:28 UTC, it-hms commented on web-docs/src/components/GitHub/UseGitHubReleaseInfo.js
> +          // Get latest version JSON from GitHub API
Handle component unmount before fetch completes. This is related to the next two/three comments
```javascript 
const controller = new AbortController();
```

2024-02-08 20:28 UTC, it-hms commented on web-docs/src/components/GitHub/UseGitHubReleaseInfo.js
> +          const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/releases/latest`);
```javascript
          const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/releases/latest`, { signal: abortController.signal });
```

2024-02-08 20:28 UTC, it-hms commented on web-docs/src/components/GitHub/UseGitHubReleaseInfo.js
> +  }, [owner, repo, cacheTimeoutMillis]);
```javascript
return () => {
      abortController.abort();
    };
```

2024-02-08 20:28 UTC, it-hms commented on web-docs/src/components/GitHub/UseGitHubReleaseInfo.js
> +          console.error("Failed to request latest release info from GitHub API", error);
```javascript
if (!abortController.signal.aborted) {
  console.error("Failed to request latest release info from GitHub API", error);
  setError(error.message);
}
```

2024-02-08 20:34 UTC, alexjhawk commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +  const versionText = latestVersionData.isLoading ? (
The variable name seems accurate to me, as this is only the version text or 'Error'/'Loading...'. 

The actual version component is built in the return statement below, using the value in `versionText`.

2024-02-08 20:34 UTC, TomKimsey requested changes

2024-02-08 20:34 UTC, TomKimsey commented on .github/ISSUE_TEMPLATE/01-app-bug-report.yml
> +        This form creates a GitHub issue in the public repository for this project.
some repos are private, 

consider rephrasing to 
This form creates a GitHub issue in the repository for this project, which may be public or shared with third party GitHub users.

2024-02-08 20:34 UTC, TomKimsey commented on .github/ISSUE_TEMPLATE/04-question-support.yml
> +description: Create a request for a question or support in the project.
I feel like support should get removed from this, I think its more appropriate to direct general connector support to the support tool as the TS team can also assist with connector support. Also international customers should be directed to their local support team first.

2024-02-08 20:34 UTC, TomKimsey commented on .github/ISSUE_TEMPLATE/05-security-report.yml
> +name: Security Report
What kind of issues do you see being reported here?

2024-02-08 20:45 UTC, alexjhawk commented on .github/ISSUE_TEMPLATE/05-security-report.yml
> +name: Security Report
Anything a user might consider a security issue on their end. For example, an expired device certificate works for 1-2 days after expiration.

The idea is that by providing more options and flexibility with our issue reporting/templates, users are more likely to properly fill out the required information for their specific scenario.

2024-02-08 20:45 UTC, TomKimsey commented on .github/ISSUE_TEMPLATE/05-security-report.yml
> +name: Security Report
The wording you added leads me to believe there really isnt any applicable content that should get reported in this form. Any security concerns should be reported confidentially via the /cybersecurity link.

2024-02-08 20:47 UTC, TomKimsey commented on .github/ISSUE_TEMPLATE/05-security-report.yml
> +name: Security Report
It might be nice to have someone notify us once they email [hms-csrt@hms-networks.com](mailto:hms-csrt@hms-networks.com) as we might not be notified of that information. Or we should at least find who is responsible for that inbox and let them know we are referencing it and we are to contact if they get a report.

2024-02-08 20:53 UTC, alexjhawk commented on .github/ISSUE_TEMPLATE/05-security-report.yml
> +name: Security Report
I think we can address the internal communication issue between us and cybersecurity reports separately or later, as it is not within the scope of this PR here. The primary goal is to outline the steps for a user to take should they encounter a security vulnerability.

While vulnerabilities should be reported via the outlined method/webpage, that doesn't eliminate the purpose of a separate security report form. 

If a user or customer feels that they have something suitable for reporting via this template, I would rather have the template available than have the issue be either not reported or reported using another template that does not provide the detail/information we are looking for.

2024-02-08 20:56 UTC, it-hms commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +  const versionText = latestVersionData.isLoading ? (
The point that I was trying to make is the variable name makes you think it is text. This text includes p and a tags. So it is more accurately hypertext. I don't think this really matters.

2024-02-08 21:04 UTC, alexjhawk commented on .github/ISSUE_TEMPLATE/04-question-support.yml
> +description: Create a request for a question or support in the project.
Would it be better to remove this form entirely then? 

I'm unsure where the line would be between `question` and `support`, so I can't imagine that would be clear for a user/customer either. I can see these issues turning into longer 'support' pretty quickly.

Maybe all questions/support are directed to local TS; if necessary, the 'other' report form is available.

2024-02-08 21:06 UTC, alexjhawk commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +  const versionText = latestVersionData.isLoading ? (
I see what you mean. I'll rename to `versionNumberComponent` to better describe that the content is for the 'version number' and that it is enclosed in a `p`/`a` component.

2024-02-08 21:30 UTC, alexjhawk commented on .github/ISSUE_TEMPLATE/04-question-support.yml
> +description: Create a request for a question or support in the project.
I think the best solution is to remove the question/support option entirely, because the line is or can become blurry between the two. I've removed that form and renumbered the rest appropriately.

2024-02-08 21:31 UTC, alexjhawk commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +  const versionText = latestVersionData.isLoading ? (
Renamed. 

Also, I have not forgotten about your other requested changes. I just focused on those from Tom K above, as he will not be around tomorrow.

2024-02-08 21:31 UTC, alexjhawk commented on .github/ISSUE_TEMPLATE/01-app-bug-report.yml
> +        This form creates a GitHub issue in the public repository for this project.
Changed

2024-02-08 21:50 UTC, TomKimsey approved these changes
Approved - Defer to @it-hms for .js files

2024-02-09 12:41 UTC, it-hms commented
here's a summary blog post about aborting fetch in react component. 
https://dev.to/pallymore/clean-up-async-requests-in-useeffect-hooks-90h

2024-02-09 13:51 UTC, alexjhawk commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +      <div
Is there a fix that should be applied here, or is this just a comment?

2024-02-09 13:53 UTC, alexjhawk commented on web-docs/src/components/GitHub/LatestVersionDisplay.js
> +      style={styles.version(
`styles.version` is applied to the `p`/`a` component here, but the containing div is different and uses `styles.versionContainer`

2024-02-09 14:22 UTC, alexjhawk commented on web-docs/src/components/GitHub/UseGitHubReleaseInfo.js
> +          // Get latest version JSON from GitHub API
Added

2024-02-09 14:22 UTC, alexjhawk commented on web-docs/src/components/GitHub/UseGitHubReleaseInfo.js
> +          const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/releases/latest`);
Added

2024-02-09 14:23 UTC, alexjhawk commented on web-docs/src/components/GitHub/UseGitHubReleaseInfo.js
> +  }, [owner, repo, cacheTimeoutMillis]);
Added

2024-02-09 14:23 UTC, alexjhawk commented on web-docs/src/components/GitHub/UseGitHubReleaseInfo.js
> +          console.error("Failed to request latest release info from GitHub API", error);
Added

2024-02-09 18:11 UTC, it-hms approved these changes

2024-02-09 21:32 UTC, merged